name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-18.04

    steps:   
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
        
      - name: Install dependencies
        run: |
          chmod +x ./scripts/install_deps.sh
          sudo ./scripts/install_deps.sh
          
      - name: Run cmake in new build dir
        run: |
          rm -rf build
          mkdir -p build/dev
          cmake -DBUILD_TESTS:BOOL=TRUE -DChrono_DIR:PATH=/usr/local/lib/cmake -B build/dev -S .
          
      - name: Build project
        run: |
          cd build/dev
          make all
          chmod +x tests/f9sim-tests
          
      - name: Run tests
        run: |
          chmod +x ./build/dev/tests/f9sim-tests
          sudo ./build/dev/tests/f9sim-tests --success
